# Numerical Python

utitlizes its own array which is c++ based and has superior performace
Pandas is directly built off Pandas
Numpy is crucial to mastering Pandas
1. Arrays
2. Indexing and Selection
3. Operations
4. Exercise

## Numpy Arrays



In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
x = np.array(my_list)
x, type(x)

(array([1, 2, 3]), numpy.ndarray)

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
list(range(0,5))
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.linspace(0,100,101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [8]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [9]:
#identity matrix - square matrix of variance with all co-variants 0
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# Random Library
np.random.rand(1)

array([0.93509819])

In [11]:
np.random.rand(5,5)

array([[0.72841226, 0.93650138, 0.03172334, 0.72887315, 0.51933443],
       [0.29857261, 0.37524395, 0.4019109 , 0.33554027, 0.4835363 ],
       [0.39545448, 0.65757114, 0.05696539, 0.85427528, 0.86832998],
       [0.18206779, 0.28734844, 0.55336445, 0.44684813, 0.26191378],
       [0.57161099, 0.47500322, 0.70190625, 0.43520334, 0.03431048]])

In [12]:
#Stanard Normal Distribution or Gaussian Distribution
np.random.randn(5)

array([ 0.99799433, -0.77684787, -0.47206147,  0.30949772, -0.24700932])

In [13]:
np.random.randint(1,100)

11

In [14]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.shape

(25,)

In [17]:
arr.reshape(25,1).shape

(25, 1)

In [18]:
arr.dtype

dtype('int64')

In [19]:
ranarr

array([ 1, 24, 48, 16, 37, 16, 24, 48, 38, 44, 32, 17, 47, 36,  2, 44,  7,
       15, 25, 17, 18, 38, 17, 32, 33, 38,  0, 41, 11, 40, 18,  9, 28,  1,
        7, 46,  2, 11, 29,  0, 25,  7, 38, 14, 39, 37, 22,  8, 41, 16,  6,
       38, 34, 28, 43, 42, 39, 44, 26, 26, 23, 17, 45,  5, 38,  5, 10, 48,
        4, 48, 37, 39, 21, 33,  5, 21, 38, 24, 15, 31, 19, 26, 27, 36, 15,
       22,  2, 36, 10, 22, 44, 11, 25, 36,  2, 43, 44,  8, 13,  0])

In [20]:
ranarr.max()

48

In [21]:
# Returns index location of max value
ranarr.argmax()

2

In [22]:
ranarr.min(), ranarr.argmin()

(0, 26)

## Numpy Operations

In [23]:
arr  = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [25]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [26]:
1 /arr

/Users/dennismacpro/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [27]:
np.log(arr)

/Users/dennismacpro/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [28]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Numpy Indexing

In [29]:
# using np for index and selection

In [30]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
#broadcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [32]:
arr = np.arange(0,11)

In [33]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [34]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
# mat[row,col]
# mat[row][col]
mat[0]

array([ 5, 10, 15])

In [36]:
mat[2,2]

45

In [37]:
mat[1,1]

25

In [38]:
slice_of_arr = arr[0:6]
slice_of_arr [:] = 99
# Note slice is a pointer to original away. so this will mutate the original
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [40]:
# Conditional Selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
bool_arr = arr > 4

In [43]:
# Only returns the array where the values happen to be true
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])